Add pydantic classes
uptrain-ai/uptrain pull request #197
Opened 2023-04-02 14:34 UTC by lokeshwarlakhi

Added pydantic classes , the pydantic is working fine with:

- [x] fraud detection 
- [ ] human orientation classification
- [ ] ride time estimation
- [ ] shopping cart recommendation
- [ ] text summarization
- [ ] finetuning LLM
- [ ] conversation summarization

so far so good , working properly (work under progress)

2023-04-03 07:23 UTC, Dominastorm requested changes
Recommended some changes to improve code readability. There is one bug in the last cell of examples/fraud_detection/run.ipynb. Works properly after fixing it. Otherwise, looks good!

2023-04-04 05:28 UTC, vipgupta commented on examples/fraud_detection/run.ipynb
Makes sense!

2023-04-04 05:30 UTC, vipgupta commented on uptrain/core/classes/managers/check_manager.py
> +            if check.dict()["type"] in [monitor.value for monitor in Monitor]:
Agreed! Would `check.type` not work?

2023-04-04 06:09 UTC, lokeshwarlakhi commented on uptrain/core/classes/managers/check_manager.py
> +            if check.dict()["type"] in [monitor.value for monitor in Monitor]:
Yes check.type is working fine.

2023-04-05 14:45 UTC, lokeshwarlakhi commented on examples/fraud_detection/run.ipynb
cfg is the right way in this, because that's how the config is initialized

2023-04-05 15:04 UTC, closed without merging